// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-Iwp6wylUC1aK-y4Ba--7cLjnKoveZQ',
    appId: '1:669223676992:web:353797444e61b528ec03a5',
    messagingSenderId: '669223676992',
    projectId: 'studexa-b5e55',
    authDomain: 'studexa-b5e55.firebaseapp.com',
    storageBucket: 'studexa-b5e55.firebasestorage.app',
    measurementId: 'G-R8PE956NDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGq6dzJJyHLnzpvR_X6hji5p9H0wIvO6w',
    appId: '1:669223676992:android:20358f050015e2a8ec03a5',
    messagingSenderId: '669223676992',
    projectId: 'studexa-b5e55',
    storageBucket: 'studexa-b5e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADw9IXbCciLEAUZlOy0H7eoSXXTsC4l5w',
    appId: '1:669223676992:ios:a1631f300c42ab4fec03a5',
    messagingSenderId: '669223676992',
    projectId: 'studexa-b5e55',
    storageBucket: 'studexa-b5e55.firebasestorage.app',
    iosBundleId: 'com.example.studexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv-Iwp6wylUC1aK-y4Ba--7cLjnKoveZQ',
    appId: '1:669223676992:web:9901f9c863b470c1ec03a5',
    messagingSenderId: '669223676992',
    projectId: 'studexa-b5e55',
    authDomain: 'studexa-b5e55.firebaseapp.com',
    storageBucket: 'studexa-b5e55.firebasestorage.app',
    measurementId: 'G-0J5P2GT50S',
  );
}
